print("Como hacer una taza de café")

print("Rdevisar si hay café")
print("Tomar una olla")
print("Poner agua en la olla hasta la mitad")
print("Poner la olla en la estufa")
print("Encender la estufa")
print("Esperar a que hierva")
print("Apagar la estufa")
print("Tomar una cuchara")
print("Abri el bote de café")
print("Tomar café con la cuchara")
print("El cafe que tomamos con la cuchara ponerlo en la estufa")
print("Mezclar")
print("Tomar una taza")
print("Servir el café de la olla en la taza")
print("Dejar de servir")
print("Cerrar el café")
print("Liato, ya quedó la taza de café")
print("Fin")